---
#These tasks will copy the code from github
#Working on another app that will deploy an app
- name: Copy the code from repository
  git: repo={{ repository }} dest=/var/www/html/ force=yes
  ignore_errors: True

- name: Creates the index.php file
  template: src=index.php.j2 dest=/var/www/html/index.php
  ignore_errors: True
