---
# These tasks install http and git modules.

- name: Install http etc
  yum: name={{ item }} state=present
  with_items:
   - httpd
   - php
   - git
   - libsemanage-python
   - libselinux-python

- name: insert firewalld rule for httpd
  firewalld: port={{ httpd_port }}/tcp permanent=true state=enabled immediate=yes

- name: http service state
  service: name=httpd state=started enabled=yes
