---
# This playbook contains common plays that will be run on all nodes.

- name: Enable firewalld service
  service:  name=firewalld state=started enabled=yes

- name: Upgrade all packages
  yum: name=* state=latest

- name: Set SELinux to enforcing
  selinux: policy=targeted state=enforcing
  register: result

- name: Reboot system due to SELinux change
  raw: /sbin/shutdown -r

- name: Wait for system to reboot (max 5 minutes / 90 sec delay)
  wait_for: host={{ ansible_default_ipv4.address }} port=22 timeout={{ 5 * 60 }} delay=90 state=started
  delegate_to: 127.0.0.1
